"""Generate settings/recipes/CLI reference from the code; --check detects documentation drift."""
from __future__ import annotations
import argparse
import dataclasses
import enum
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
import models
from cli import build_parser
from presets import RECIPES, PROCESSING_PRESETS, OUTPUT_PROFILES
from models import dataclass_to_dict


def render() -> str:
    out = ['# Configuration reference', '',
           'Generated by `python tools/generate_reference.py`. Do not hand-edit the tables.', '',
           'Defaults below are **model defaults**. A recipe overrides them; see the recipe table.', '',
           'Use the desktop Job Settings or the Python API for the complete model. The CLI exposes a subset.', '']
    for name in ['SourceSpec', 'CaptureConfig', 'TimelineConfig', 'RenderConfig', 'ProcessingConfig', 'AudioConfig']:
        cls = getattr(models, name)
        value = cls(value='source.html') if name == 'SourceSpec' else cls()
        data = dataclass_to_dict(value)
        out += [f'## {name}', '', '| Field | Type | Default |', '| --- | --- | --- |']
        for f in dataclasses.fields(cls):
            default = json.dumps(data[f.name], ensure_ascii=False) if not isinstance(data[f.name], dict) else '(nested settings)'
            out.append(f'| `{f.name}` | `{str(f.type)}` | `{default}` |')
        out += ['']
    out += ['## Enumerations', '']
    for name in ['SourceKind','LoadStrategy','CaptureMode','TimelineMode','GeometryMode','AudioMode','JobStatus']:
        out += [f'**{name}:** '+', '.join('`'+v.value+'`' for v in getattr(models,name)), '']
    out += ['## Recipes', '', '| Key | Capture / timeline | Scale / fps | Codec | Processing | Explicit duration |',
            '| --- | --- | --- | --- | --- | --- |']
    for key, recipe in RECIPES.items():
        j = recipe.create_job('source.html')
        out.append(f'| `{key}` | `{j.capture.mode.value}` / `{j.timeline.mode.value}` | {j.render.scale:g}× / {j.render.fps} | `{j.render.output_profile_key}` | `{j.render.processing.preset_key}` | {j.timeline.manual_duration if j.timeline.manual_duration is not None else "None; must resolve from source/user"} |')
    out += ['', '## Processing presets', '', '| Key | Method | Strength |', '| --- | --- | --- |']
    for key, preset in PROCESSING_PRESETS.items():
        out.append(f'| `{key}` | {"automatic selection" if preset.auto else preset.sharpen_method} | {preset.sharpen_strength:g} |')
    out += ['', '## Codec configuration', '']
    for key, profile in OUTPUT_PROFILES.items():
        out += [f'### `{key}`', '', profile.description, '',
                f'Extension: `{profile.extension}`. Alpha: `{profile.supports_alpha}`. Even dimensions required: `{profile.requires_even_dimensions}`.', '',
                'Video arguments:', '```text', ' '.join(profile.video_args), '```', '',
                'Audio arguments:', '```text', ' '.join(profile.audio_args), '```', '']
    out += ['## CLI help', '', '```text', build_parser().format_help().rstrip(), '```', '']
    return '\n'.join(out)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args(argv)
    path = ROOT/'docs/CONFIGURATION.md'; text = render()
    if args.check:
        if not path.exists() or path.read_text(encoding='utf-8') != text:
            print('Configuration reference is stale. Run: python tools/generate_reference.py', file=sys.stderr)
            return 1
        print('Configuration reference matches code.')
    else:
        path.parent.mkdir(exist_ok=True)
        path.write_text(text, encoding='utf-8')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
